import hre from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const { ethers } = hre;
  const [deployer] = await ethers.getSigners();

  console.log("Deploying ObeliskSBT with account:", deployer.address);
  console.log("Account balance:", (await ethers.provider.getBalance(deployer.address)).toString());

  const ObeliskSBT = await ethers.getContractFactory("ObeliskSBT");
  const sbt = await ObeliskSBT.deploy(deployer.address);
  await sbt.waitForDeployment();

  const contractAddress = await sbt.getAddress();
  console.log("✅ ObeliskSBT deployed to:", contractAddress);
  console.log("🔗 View on Snowtrace:", `https://testnet.snowtrace.io/address/${contractAddress}`);

  // ── Write deployed address to lib/blockchain/sbt.ts for the app to use ──
  const outputPath = path.resolve(__dirname, "../../lib/blockchain/sbt.ts");
  const outputContent = `// Auto-generated by contracts/scripts/deploy.ts — DO NOT EDIT MANUALLY
// Deployed on: ${new Date().toISOString()}
// Network: Avalanche Fuji Testnet (chainId: 43113)

export const SBT_CONTRACT_ADDRESS = "${contractAddress}" as const;
export const SBT_CHAIN_ID = 43113 as const;

export const SBT_ABI = [
  "function safeMint(address to, string calldata uri, string calldata postId) external returns (uint256)",
  "function tokenURI(uint256 tokenId) external view returns (string)",
  "function totalMinted() external view returns (uint256)",
  "function ownerOf(uint256 tokenId) external view returns (address)",
  "event SBTMinted(address indexed recipient, uint256 indexed tokenId, string tokenURI, string postId)",
] as const;
`;

  fs.writeFileSync(outputPath, outputContent);
  console.log("✅ ABI + address written to lib/blockchain/sbt.ts");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
