// Auto-generated by contracts/scripts/deploy.ts — DO NOT EDIT MANUALLY
// Deployed on: 2026-05-08T16:28:06.700Z
// Network: Avalanche Fuji Testnet (chainId: 43113)

export const SBT_CONTRACT_ADDRESS = "0x2c3ce0B7b58B148f90fc3B9F617eD835Ef6a6B32" as const;
export const SBT_CHAIN_ID = 43113 as const;

export const SBT_ABI = [
  "function safeMint(address to, string calldata uri, string calldata postId) external returns (uint256)",
  "function tokenURI(uint256 tokenId) external view returns (string)",
  "function totalMinted() external view returns (uint256)",
  "function ownerOf(uint256 tokenId) external view returns (address)",
  "event SBTMinted(address indexed recipient, uint256 indexed tokenId, string tokenURI, string postId)",
] as const;
